[package]
name = "distrib-kv-rust"
version = "0.1.0"
edition = "2024"
default-run = "distrib-kv-rust"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
rand = "0.8"
clap = { version = "4.4", features = ["derive"] }